require 'vagrant-deltacloud-provider'

Vagrant.configure('2') do |config|

  config.vm.box = 'deltacloud'
  config.vm.box_url = 'https://github.com/cybercom-finland/vagrant-deltacloud-provider/raw/master/source/dummy.box'

  config.ssh.private_key_path = ENV['OS_KEYPAIR_PRIVATE_KEY']
  config.ssh.pty = true
  config.ssh.shell = ENV['OS_SSH_SHELL']

  config.vm.provider :deltacloud do |os|
    os.username               = ENV['OS_USERNAME']
    os.password               = ENV['OS_PASSWORD']
    os.deltacloud_api_url     = ENV['OS_API_URL']
    os.tenant_name            = ENV['OS_TENANT_NAME']
    os.ssh_timeout            = ENV['OS_SSH_TIMEOUT'].to_i
    os.sync_method            = ENV['OS_SYNC_METHOD']
    os.hardware_profile       = ENV['OS_HARDWARE_PROFILE']
    os.image                  = ENV['OS_IMAGE']
    os.ssh_username           = ENV['OS_SSH_USERNAME']
    os.public_key_name        = ENV['OS_PUBLIC_KEY_NAME']
  end

  config.vm.define 'test-basic' do |test|
    test.vm.provision 'shell', inline: 'echo "SUCCESS" > /tmp/test_shell_provision'
  end

  config.vm.define 'test-ssh-public-key-path' do |test|
    test.vm.provider :deltacloud do |os|
      os.public_key_name     = nil
      os.public_key_path  = ENV['OS_PUBLIC_KEY_PATH']
    end
    test.vm.provision 'shell', inline: 'echo "SUCCESS" > /tmp/test_shell_provision'
  end

  config.vm.define 'test-availabilty-zone' do |test|
    test.vm.provider :deltacloud do |os|
      os.availability_zone = ENV['OS_AZ']
    end
    test.vm.provision 'shell', inline: 'echo "SUCCESS" > /tmp/test_shell_provision'
  end
end
