#!/bin/bash

#Provider examples:
#Cybercom
export OS_API_URL=https://standard.fi-central.cybercomcloud.com/api
#....

if [ -z "$OS_USERNAME" ]; then
  echo "Please enter your Deltacloud tenant name: "
  read -sr OS_TENANT_NAME_INPUT
  export OS_TENANT_NAME=$OS_TENANT_NAME_INPUT
fi

if [ -z "$OS_USERNAME" ]; then
  echo "Please enter your Deltacloud username: "
  read -sr OS_USERNAME_INPUT
  export OS_USERNAME=$OS_USERNAME_INPUT
fi

if [ -z "$OS_PASSWORD" ]; then
  echo "Please enter your Deltacloud Password: "
  read -sr OS_PASSWORD_INPUT
  export OS_PASSWORD=$OS_PASSWORD_INPUT
fi
