require 'vagrant-deltacloud-provider'

Vagrant.configure('2') do |config|

  config.vm.box = 'deltacloud'

  config.ssh.username = ENV['OS_SSH_USERNAME']

  config.vm.provider :deltacloud do |os|
    os.deltacloud_api_url    = ENV['OS_API_URL']
    os.tenant_name           = ENV['OS_TENANT_NAME']
    os.username              = ENV['OS_USERNAME']
    os.password              = ENV['OS_PASSWORD']
    os.floating_ip_pool      = ENV['OS_FLOATING_IP_POOL']
    os.flavor                = ENV['OS_FLAVOR']
    os.image                 = ENV['OS_IMAGE']
  end

  config.vm.provision "shell", inline: "echo 'ok' > ~/provision"
end
